#CUDA_VISIBLE_DEVICES=1 fairseq-hydra-train common.fp16=true task.data=/media/data1/achilsowa/datasets/fairseq/mhi-mimic-code15/manifest/finetune/afib-v2 model.no_pretrained_weights=true +task.df_dataset=true model.num_labels=2 criterion._name=binary_cross_entropy_with_logits checkpoint.save_dir=checkpoint_e2e-e2e-afib-v2-bce --config-dir examples/w2v_cmsc/config/finetuning/ecg_transformer --config-name diagnosis
#CUDA_VISIBLE_DEVICES=1 fairseq-hydra-train common.fp16=true task.data=/media/data1/achilsowa/datasets/fairseq/mhi-mimic-code15/manifest/finetune/afib-v2 model.model_path=/media/data1/achilsowa/results/fairseq/outputs/2024-09-22/03-16-32/checkpoints-all/checkpoint_last.pt model.linear_evaluation=true +task.df_dataset=true model.num_labels=2 criterion._name=binary_cross_entropy_with_logits checkpoint.save_dir=checkpoint_last-le-afib-v2-bce --config-dir examples/w2v_cmsc/config/finetuning/ecg_transformer --config-name diagnosis
CUDA_VISIBLE_DEVICES=1 fairseq-hydra-train common.fp16=true task.data=/media/data1/achilsowa/datasets/fairseq/mhi-mimic-code15/manifest/finetune/afib-v2 model.model_path=/media/data1/achilsowa/results/fairseq/outputs/2024-09-22/03-16-32/checkpoints-all/checkpoint_last.pt +task.df_dataset=true model.num_labels=2 criterion._name=binary_cross_entropy_with_logits checkpoint.save_dir=checkpoint_last-ft-afib-v2-bce --config-dir examples/w2v_cmsc/config/finetuning/ecg_transformer --config-name diagnosis
CUDA_VISIBLE_DEVICES=1 fairseq-hydra-train common.fp16=true task.data=/media/data1/achilsowa/datasets/fairseq/mhi-mimic-code15/manifest/finetune/afib-v2-5 model.model_path=/media/data1/achilsowa/results/fairseq/outputs/2024-09-22/03-16-32/checkpoints-all/checkpoint_last.pt +task.df_dataset=true model.num_labels=1 criterion._name=binary_cross_entropy_with_logits checkpoint.save_dir=checkpoint_last-ft-afib-v2-5-bce --config-dir examples/w2v_cmsc/config/finetuning/ecg_transformer --config-name diagnosis

CUDA_VISIBLE_DEVICES=1 fairseq-hydra-train common.fp16=true task.data=/media/data1/achilsowa/datasets/fairseq/mhi-mimic-code15/manifest/finetune/afib-v2 model.no_pretrained_weights=true +task.df_dataset=true model.num_labels=2 criterion._name=binary_focal checkpoint.save_dir=checkpoint_e2e-e2e-afib-v2-bf --config-dir examples/w2v_cmsc/config/finetuning/ecg_transformer --config-name diagnosis
CUDA_VISIBLE_DEVICES=1 fairseq-hydra-train common.fp16=true task.data=/media/data1/achilsowa/datasets/fairseq/mhi-mimic-code15/manifest/finetune/afib-v2 model.model_path=/media/data1/achilsowa/results/fairseq/outputs/2024-09-22/03-16-32/checkpoints-all/checkpoint_last.pt model.linear_evaluation=true +task.df_dataset=true model.num_labels=2 criterion._name=binary_focal checkpoint.save_dir=checkpoint_last-le-afib-v2-bf --config-dir examples/w2v_cmsc/config/finetuning/ecg_transformer --config-name diagnosis
CUDA_VISIBLE_DEVICES=1 fairseq-hydra-train common.fp16=true task.data=/media/data1/achilsowa/datasets/fairseq/mhi-mimic-code15/manifest/finetune/afib-v2 model.model_path=/media/data1/achilsowa/results/fairseq/outputs/2024-09-22/03-16-32/checkpoints-all/checkpoint_last.pt +task.df_dataset=true model.num_labels=2 criterion._name=binary_focal checkpoint.save_dir=checkpoint_last-ft-afib-v2-bf --config-dir examples/w2v_cmsc/config/finetuning/ecg_transformer --config-name diagnosis
CUDA_VISIBLE_DEVICES=1 fairseq-hydra-train common.fp16=true task.data=/media/data1/achilsowa/datasets/fairseq/mhi-mimic-code15/manifest/finetune/afib-v2-5 model.model_path=/media/data1/achilsowa/results/fairseq/outputs/2024-09-22/03-16-32/checkpoints-all/checkpoint_last.pt +task.df_dataset=true model.num_labels=1 criterion._name=binary_focal checkpoint.save_dir=checkpoint_last-ft-afib-v2-5-bf --config-dir examples/w2v_cmsc/config/finetuning/ecg_transformer --config-name diagnosis
